name: Amazing Favorites publish with AOT test

on:
  push:
    branches:
      - feature/aot

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/src
          dotnet workload install microsoft-net-sdk-blazorwebassembly-aot
          dotnet restore
      - name: build and test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
        run: |
          dotnet publish Newbe.BookmarkManager -c Release -o out -p:EnableAOT=true
