name: Release

on:
  push:
    branches:
      - publish_test

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        enable-aot: [ 'true','false' ]
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100-preview.7.21379.14'
          include-prerelease: true
      - name: Setup .NET 5.0 for Release Manager
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: 5.x
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.10
        with:
          useConfigFile: true
      - name: Restore dependencies
        run: |
          cd $GITHUB_WORKSPACE/src
          dotnet workload install wasm-tools
          dotnet restore
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE/src
          dotnet publish Newbe.BookmarkManager -c Release -o out -p:AssemblyVersion=${{ steps.gitversion.outputs.MajorMinorPatch }} -p:Version=${{ steps.gitversion.outputs.SemVer }} -p:EnableAOT=${{ matrix.enable-aot }}
          mv out/browserextension Amazing-Favorites-${{ steps.gitversion.outputs.MajorMinorPatch }}
          zip -r Amazing-Favorites-${{ steps.gitversion.outputs.MajorMinorPatch }}-aot-${{ matrix.enable-aot }}.zip Amazing-Favorites-${{ steps.gitversion.outputs.MajorMinorPatch }}
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            src/Amazing-Favorites-${{ steps.gitversion.outputs.MajorMinorPatch }}-aot-${{ matrix.enable-aot }}.zip